name: CI/CD
on: 
  pull_request:
    branches: [ main ]
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      
    - name: Set up Java JDK
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Gradle
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: AppetiserChallenge-release.apk
        path: app/build/outputs/apk/release/app-release.apk
